### ISSUE TITLE
Github-bot

### ISSUE THREAD

**Issue by roopamgarg** [Code-Linguists/Code-Snippets#5]
**Is your feature request related to a problem? Please describe.**
I want my Github contribution graph completely green just to show off my peers 😎

**Describe the solution you'd like**
We can tweak the date of commits before committing them using the --date option. So we can write a script that does some changes in our repo and commit them after every change for dates for the last 1 year to today

**Comment by simran130810** [comment]
I want to solve that issue

**Comment by roopamgarg** [comment]
sure
