### ISSUE TITLE
Delete all the node_modules folder inside the current folder

### ISSUE THREAD

**Issue by roopamgarg** [Code-Linguists/Code-Snippets#6]
**Is your feature request related to a problem? Please describe.**
node_modules folders are frustrating when you are taking backup of all your node.js projects in the local system. It takes a lot of time to delete them one by one

**Describe the solution you'd like**
Write a bash command for this task is an easy way to achieve this task

**Describe alternatives you've considered**
This might also be done by using any other languages that can deal with the filesystem

**Comment by Zer0Palm** [comment]
Hey, I want to contribute on this issue.

**Comment by roopamgarg** [comment]
Sure!
